### ISSUE TITLE
Issue Deploying Alert

### ISSUE THREAD

**Issue by mphammer** [blackducksoftware/synopsys-operator#412]
**What happened**:
Synopsysctl is giving the error "Error loading config file"

**What you expected to happen**:
Alert is successfully deployed

```
time="2019-05-09T11:30:32-04:00" level=error msg="error getting Kube Client: No Auth Provider found for name \"oidc\""
time="2019-05-09T11:30:32-04:00" level=error msg="error creating the Blackduck Clientset: No Auth Provider found for name \"oidc\""
time="2019-05-09T11:30:32-04:00" level=error msg="error creating the OpsSight Clientset: No Auth Provider found for name \"oidc\""
time="2019-05-09T11:30:32-04:00" level=error msg="error creating the Alert Clientset: No Auth Provider found for name \"oidc\""
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xa8 pc=0x1007826]

goroutine 1 [running]:
github.com/blackducksoftware/synopsys-operator/vendor/k8s.io/client-go/kubernetes.(*Clientset).Rbac(...)
/go/src/github.com/blackducksoftware/synopsys-operator/vendor/k8s.io/client-go/kubernetes/clientset.go:336
github.com/blackducksoftware/synopsys-operator/pkg/util.GetClusterRoleBinding(0x0, 0x168a461, 0x17, 0xd, 0x1, 0xc0000d3990)
/go/src/github.com/blackducksoftware/synopsys-operator/pkg/util/common.go:904 +0x36
github.com/blackducksoftware/synopsys-operator/pkg/synopsysctl.GetOperatorNamespace(0x1680cf0, 0x10, 0x1698bac, 0xffffffffffffffff)
/go/src/github.com/blackducksoftware/synopsys-operator/pkg/synopsysctl/utils.go:108 +0x4d
github.com/blackducksoftware/synopsys-operator/pkg/synopsysctl.glob..func16(0x256cdc0, 0x259eb60, 0x0, 0x0, 0x0, 0x0)
/go/src/github.com/blackducksoftware/synopsys-operator/pkg/synopsysctl/cmd_deploy.go:91 +0x76
github.com/blackducksoftware/synopsys-operator/vendor/github.com/spf13/cobra.(*Command).execute(0x256cdc0, 0x259eb60, 0x0, 0x0, 0x256cdc0, 0x259eb60)
/go/src/github.com/blackducksoftware/synopsys-operator/vendor/github.com/spf13/cobra/command.go:762 +0x47a
github.com/blackducksoftware/synopsys-operator/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x256ffa0, 0xc00034da00, 0x2570200, 0x2571500)
/go/src/github.com/blackducksoftware/synopsys-operator/vendor/github.com/spf13/cobra/command.go:852 +0x304
github.com/blackducksoftware/synopsys-operator/vendor/github.com/spf13/cobra.(*Command).Execute(0x256ffa0, 0xc000072058, 0x0)
/go/src/github.com/blackducksoftware/synopsys-operator/vendor/github.com/spf13/cobra/command.go:800 +0x32
github.com/blackducksoftware/synopsys-operator/pkg/synopsysctl.Execute()
/go/src/github.com/blackducksoftware/synopsys-operator/pkg/synopsysctl/cmd_root.go:67 +0x38
main.main()
/go/src/github.com/blackducksoftware/synopsys-operator/cmd/synopsysctl/main.go:29 +0x27
Edit | Del | Make Private	Checked	Created By: Support Automation (5/8/2019 11:14 AM)
From: Kruse,Thad C <tkruse@travelers.com>
To: software-integrity-support@synopsys.com
```

```
C:\Users\tkruse\BlackDuck\synopsys-operator-2019.4.1\synopsysctl-windows-amd64>synopsysctl.exe 
deploy time="2019-05-20T08:43:26-04:00" level=error msg="Error loading config file \"C:\\Users\\tkruse;C:\\Users\\tkruse\\.kube\\config\": 
open C:\\Users\\tkruse;C:\\Users\\tkruse\\.kube\\config: The filename, directory name, or volume label syntax is incorrect."

C:\Users\tkruse\BlackDuck\synopsys-operator-2019.4.1\synopsysctl-windows-amd64>synopsysctl create alert blackduck-dev
time="2019-05-20T10:33:54-04:00" level=error msg="Error loading config 
file \"C:\\Users\\tkruse;C:\\Users\\tkruse\\.kube\\config\": 
open C:\\Users\\tkruse;C:\\Users\\tkruse\\.kube\\config: The filename, directory name, or volume label syntax is incorrect."
```

**Environment (please complete the following information):**
Trying to deploy Alert on Kubernetes using Operator 2.

**Comment by mphammer** [comment]
Update: 
1. The issues above are outdated. Customers are seeing new issues where they cannot deploy the operator but they appear to be able to create an Alert. 
2. We were able to reproduce the issue by creating an Synopsys Operator with an old install.sh script, deleting the namespace of the Synopsys Operator, and then running commands with synosysctl. 
3. We have a meeting today with the Customers to better understand the issue

**Comment by mphammer** [comment]
We gave the customer instructions on how to resolve the issue and prevent it in the future.
